version: '3.7'

services:
  collection_leds:
    build:
      context: ./services/collection_leds
      dockerfile: Dockerfile.mount
    # command: gunicorn --bind 0.0.0.0:5000 app:app
    command: python app.py
    restart: unless-stopped
    volumes:
      - ./services/collection_leds/:/usr/src/app/
    expose:
      - 5000
    env_file:
      - ./.env
    devices:
      - /dev/gpiomem
    privileged: true
    networks:
      - bridge
  #   depends_on:
  #     - db
  # db:
  #   image: postgres:12-alpine
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   env_file:
  #     - ./.env.prod.db
  nginx:
    build: ./services/nginx
    restart: always
    # volumes:
    #   - static_volume:/home/app/web/project/backend/static
    ports:
      - 80:80
    networks:
      - bridge
    # depends_on:
    #   - ui
  # ui:
  #   build: ./services/ui
  #   container_name: ui
  #   restart: always
  #   expose:
  #     - 80
  #   depends_on:
  #     - web
  node-red:
    build:
      context: ./services/node_red
      dockerfile: Dockerfile
    restart: always
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1880:1880"
    networks:
      - node-red-net
      - bridge
    volumes:
      - node-red-data:/data

volumes:
  # postgres_data:
  static_volume:
  node-red-data:

networks:
  node-red-net:
  bridge: